# Rocket Hunter v1 CONFIG

EXCHANGE = "bybit"
MARKET_TYPE = "spot"

SCAN_INTERVAL_SECONDS = 10
MAX_SYMBOLS_TO_SCAN = 300

SCORE_THRESHOLD_ENTRY = 70
SCORE_THRESHOLD_AGGRESSIVE = 85

POSITION_SIZE_PERCENT = 0.30
MAX_OPEN_POSITIONS = 3

STOP_LOSS_PERCENT = 0.8
TAKE_PROFIT_TARGETS = [0.8, 1.5, 2.5]

TRAILING_START_PERCENT = 1.0
TRAILING_CALLBACK_PERCENT = 0.4

DAILY_MAX_LOSS_PERCENT = 5
COOLDOWN_AFTER_LOSS_MINUTES = 10

VOLUME_SPIKE_MULTIPLIER = 2.5
MIN_24H_VOLUME_USDT = 1000000

MAX_SPREAD_PERCENT = 0.5

ENABLE_KILL_SWITCH = True
KILL_SWITCH_ON_DRAWDOWN = 10